# 路由信息
route:
  crm:
    "0731": crm42
    "0732": crm42
    "0733": crm42
    "0734": crm42
    "0735": crm42
    "0736": crm42
    "0737": crm42
    "0738": crm42
    "0739": crm42
    "0730": crm42
    "0743": crm42
    "0744": crm42
    "0745": crm42
    "0746": crm42
    "cg": crmg
    "HNAN": crm42
    "07XX": crm42
  jour:
    "0731": jour42
    "0971": jour42
    "0732": jour42
    "0735": jour42
    "cg": jourg
    "HNAN": jour42
    "07XX": jour42

#序列前缀
center:
  order:
    sequencePrefix:
      "0730": "30"
      "0731": "31"
      "0971": "31"
      "0732": "32"

#归档、备份表对应关系
table-mapping:
  order:
    user:
        TF_B_TRADE_ACCOUNT_CONSIGN: TF_F_ACCOUNT_CONSIGN
        TF_B_TRADE_BROADBAND : TF_F_USER_BROADBAND
        TF_B_TRADE_BROADBAND_ACT : TF_F_USER_BROADBAND_ACT
        TF_B_TRADE_BLACKWHITE : TF_F_USER_BLACKWHITE
        TF_B_TRADE_GRP_MEB_PLATSVC : TF_F_USER_GRP_MEB_PLATSVC
        TF_B_TRADE_USER_PAYITEM : TF_F_USER_PAYITEM
        TF_B_TRADE_USER_PAYPLAN : TF_F_USER_PAYPLAN
        TF_B_TRADE_SCORERELATION : TF_F_SCORERELATION
        TF_B_TRADE_OFFER_REL : TF_F_USER_OFFER_REL
        TF_B_TRADE_GRP_MERCH : TF_F_USER_GRP_MERCH
        TF_B_TRADE_GRP_MERCH_DISCNT : TF_F_USER_GRP_MERCH_DISCNT
        TF_B_TRADE_VPN : TF_F_USER_VPN
        TF_B_TRADE_GRP_MERCH_MB_DIS : TF_F_USER_GRP_MERCH_MB_DIS
        TF_B_TRADE_VPN_MEB : TF_F_USER_VPN_MEB
        TF_B_TRADE_GRP_MERCH_MEB : TF_F_USER_GRP_MERCH_MEB
        TF_B_TRADE_GRP_MERCHP : TF_F_USER_GRP_MERCHP
        TF_B_TRADE_SALE_GOODS : TF_F_USER_SALE_GOODS
        TF_B_TRADE_ACCOUNT_ACCTDAY : TF_F_ACCOUNT_ACCTDAY
        TF_B_TRADE_OTHER : TF_F_USER_OTHER
        TF_B_TRADE_GRP_PACKAGE : TF_F_USER_GRP_PACKAGE
        TF_B_TRADE_IMPU : TF_F_USER_IMPU
        TF_B_TRADE_RATE : TF_F_USER_RATE
        TF_B_TRADE_RELATION_AA : TF_F_RELATION_AA
        TF_B_TRADE_GRP_PLATSVC : TF_F_USER_GRP_PLATSVC
        TF_B_TRADE_RELATION_BB : TF_F_RELATION_BB
        TF_B_TRADE_RENT : TF_F_USER_RENT
        TF_B_TRADE_DISCNT : TF_F_USER_DISCNT
        TF_B_TRADE_PAYRELATION : TF_A_PAYRELATION
        TF_B_TRADE_INTEGRALACCT : TF_F_INTEGRAL_ACCT
        TF_B_TRADE_INTEGRALPLAN : TF_F_INTEGRAL_PLAN
        TF_B_TRADE_RES : TF_F_USER_RES
        TF_B_TRADE_SALE_DEPOSIT : TF_F_USER_SALE_DEPOSIT
        TF_B_TRADE_PLATSVC : TF_F_USER_PLATSVC
        TF_B_TRADE_MEB_CENPAY : TF_F_USER_MEB_CENPAY
        TF_B_TRADE_OCS : TF_F_USER_OCS
        TF_B_TRADE_POST : TF_F_POSTINFO
        TF_B_TRADE_RELATION : TF_F_RELATION_UU
        TF_B_TRADE_GRP_MERCHP_DISCNT : TF_F_USER_GRP_MERCHP_DISCNT
        TF_B_TRADE_GRP_MOLIST : TF_F_USER_GRP_MOLIST
        TF_B_TRADE_PRODUCT : TF_F_USER_PRODUCT
        TF_B_TRADE_SHARE : TF_F_USER_SHARE
        TF_B_TRADE_ACCOUNT : TF_F_ACCOUNT
        TF_B_TRADE_SHARE_INFO : TF_F_USER_SHARE_INFO
        TF_B_TRADE_SHARETYPE : TF_F_USER_SHARETYPE
        TF_B_TRADE_SALE_ACTIVE : TF_F_USER_SALE_ACTIVE
        TF_B_TRADE_GRP_CENPAY : TF_F_USER_GRP_CENPAY
        TF_B_TRADE_SHARE_RELA : TF_F_USER_SHARE_RELA
        TF_B_TRADE_IPTV : TF_F_USER_IPTV
        TF_B_TRADE_SHARE_POOL : TF_F_SHARE_POOL
        TF_B_TRADE_SHARE_POOL_USE : TF_F_SHARE_POOL_USE
        TF_B_TRADE_SHARE_POOL_SUPPLY : TF_F_USER_SHARE_POOL_SUPPLY
        TF_B_TRADE_BANK_MAINSIGN : TF_F_BANK_MAINSIGN
        TF_B_TRADE_SVC : TF_F_USER_SVC
        TF_B_TRADE_USER : TF_F_USER
        TF_B_TRADE_BANK_SUBSIGN : TF_F_BANK_SUBSIGN
        TF_B_TRADE_ATTR : TF_F_USER_ATTR
        TF_B_TRADE_USER_ACCTDAY : TF_F_USER_ACCTDAY
        TF_B_TRADE_SVCSTATE : TF_F_USER_SVCSTATE
        TF_B_TRADE_BIGMARKET_RELATION : TF_F_USER_BIGMARKET_RELATION
        TF_B_TRADE_ECRECEP_OFFER : TF_F_USER_ECRECEP_OFFER
        TF_B_TRADE_ECRECEP_PRODUCT : TF_F_USER_ECRECEP_PRODUCT
        TF_B_TRADE_ECRECEP_MEB : TF_F_USER_ECRECEP_MEB
        TF_B_TRADE_ECRECEP_PROCEDURE : TF_F_USER_ECRECEP_PROCEDURE
    bak:
        TF_F_USER: TF_F_USER_BAK
    sync:
        TF_B_TRADE_USER: TI_B_USER

partition-mapping:
  order:
    trade:
      TF_B_TRADE_ACCOUNT: ACCT_ID
      TF_B_TRADE_INTEGRALACCT: INTEGRAL_ACCT_ID
      TF_B_TRADE_ACCOUNT_CONSIGN: ACCT_ID
      TF_B_TRADE_SHARE_POOL_USE: USE_INST_ID
      TF_B_TRADE_SHARE_POOL_SUPPLY: SUPPLY_INST_ID
      TF_B_TRADE_RELATION_AA: ACCT_ID_B
      TF_B_TRADE_RELATION: USER_ID_B
      TF_B_TRADE_RELATION_BB: USER_ID_B
      TF_B_TRADE_POST: ID
      TF_B_TRADE_SHARE_RELA: USER_ID_B
      TF_B_TRADE_SHARETYPE: USER_ID_B
      TF_B_TRADE_SHARE_MEBLIMIT: USER_ID_B
      TF_B_TRADE_CUST_FAMILY: HOME_CUST_ID
      TF_B_TRADE_ACCOUNT_ACCTDAY: ACCT_ID
      TF_B_TRADE_NETNP: IN_USER_ID
    user:
      TF_F_ACCOUNT: ACCT_ID
      TF_F_INTEGRAL_ACCT: INTEGRAL_ACCT_ID
      TF_F_ACCOUNT_CONSIGN: ACCT_ID
      TF_F_SHARE_POOL_USE: USE_INST_ID
      TF_F_USER_SHARE_POOL_SUPPLY: SUPPLY_INST_ID
      TF_F_RELATION_AA: ACCT_ID_B
      TF_F_RELATION_UU: USER_ID_B
      TF_F_RELATION_BB: USER_ID_B
      TF_F_USER_SHARETYPE: USER_ID_B
      TF_F_USER_SHARE_RELA: USER_ID_B
      TF_F_USER_SHARE_MEBLIMIT: USER_ID_B
      TF_F_CUST_FAMILY: HOME_CUST_ID
      TF_F_ACCOUNT_ACCTDAY: ACCT_ID
      TF_F_USER_NETNP: IN_USER_ID